## Exercises

### Importing

In [68]:
import numpy as np

### Matrix Multiplication

In [69]:
mat1 = np.array([
        [3,2,1,5],
        [9,1,3,0]
        ])
mat2 = np.array([
        [2,9,0],
        [1,3,5],
        [2,4,7],
        [8,1,5]
        ])

resault = np.dot(mat1,mat2)
print(mat1)
print(20*'-')
print(mat2)
print(20*'-')
print(resault)

[[3 2 1 5]
 [9 1 3 0]]
--------------------
[[2 9 0]
 [1 3 5]
 [2 4 7]
 [8 1 5]]
--------------------
[[50 42 42]
 [25 96 26]]


### Matrix Determinan

In [70]:
mat = np.array([
                    [3,8,-6],
                    [4,10,-1],
                    [-1,9,7]
                ])

print(mat)
print(20*'-')
print(np.linalg.det(mat)) 

[[ 3  8 -6]
 [ 4 10 -1]
 [-1  9  7]]
--------------------
-254.99999999999991


### Matrix Invers

In [51]:
mat = np.array([
                    [2,3,1],
                    [3,4,1],
                    [3,7,2]
                ])

print(mat)
print(20*'-')
print(np.linalg.inv(mat)) 

[[2 3 1]
 [3 4 1]
 [3 7 2]]
--------------------
[[ 0.5  0.5 -0.5]
 [-1.5  0.5  0.5]
 [ 4.5 -2.5 -0.5]]


### Eigenvalues

In [57]:
mat = np.array([
                    [0,1],
                    [-2,-3]
                ])

print(mat)
print(20*'-')
w, v = np.linalg.eig(mat)
print(f'Eigenvalues: {w}')

[[ 0  1]
 [-2 -3]]
--------------------
Eigenvalues: [-1. -2.]


### Matrix Norm

In [61]:
mat = np.array([
                    [5,3,6],
                    [0,-2,1],
                    [4,7,2]
                ])
norm = np.linalg.norm(mat)
norm_row = np.linalg.norm(mat,axis=0)
norm_col = np.linalg.norm(mat,axis=1)

print(mat)
print(34*'-',end='\n\n')

print('Norm:')
print(norm) 
print(4*'-',end='\n\n')

print('Norm Row:')
print(norm_row) 
print(34*'-',end='\n\n')

print('Norm Col:')
print(norm_col) 
print(34*'-')

[[ 5  3  6]
 [ 0 -2  1]
 [ 4  7  2]]
----------------------------------

Norm:
12.0
----

Norm Row:
[6.40312424 7.87400787 6.40312424]
----------------------------------

Norm Col:
[8.36660027 2.23606798 8.30662386]
----------------------------------


### Solve

In [67]:
a = np.array([
    [1, -1, 1],
    [3, 1, 2],
    [-5, 2, -1]
])
b = np.array([10,34,-14])
resault = np.linalg.solve(a,b)
x, y, z = resault
print(f'x = {x}, y = {y}, z = {z}')

x = 2.0, y = 4.0, z = 12.0
